### ISSUE TITLE
How can I add proxy?

### ISSUE THREAD

**Issue by cxreed1** [kawsarlog/amazon-reviews-extraction#1]

**Comment by kawsarlog** [comment]
to use a proxy: 
you can follow given below code:

http_proxy  = "http://00.000.1.10:8080"
https_proxy = "https://00.000.1.10:8080"

proxies = { 
              "http"  : http_proxy, 
              "https" : https_proxy, 
            }

r = requests.get(url, headers=headers, proxies=proxies)
